# This is a basic workflow to help you get started with Actions

name: cd

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [staging] 
    
env:
  GITHUB_TOKEN: ${{ secrets.PAT }}
  HAS_CHANGES: true

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  createrelease:
    runs-on: ubuntu-latest

    steps:
      - name: git checkout
        uses: actions/checkout@v2
        with:
          token: ${{ env.GITHUB_TOKEN }}
          ref: ${{ github.event.pull_request.head.ref }}
          fetch-depth: 0

      - name: Create release branch
        uses: peterjgrainger/action-create-branch@v2.2.0
        with:
          branch: 'release-candidate'
          sha: '${{ github.event.pull_request.head.sha }}'
          
      - name: Check for changes
        run: |
          if [ -z "$(git --no-pager log --left-right --cherry-pick --oneline release-candidate...staging)" ]
            echo "::set-env name=HAS_CHANGES::false"
          else
            echo "::set-env name=HAS_CHANGES::true"
          fi

      - name: Rebase
        if: ${{ env.HAS_CHANGES == 'true' }}
        run: |
          git fetch origin staging
          git fetch origin release-candidate
          git checkout release-candidate
          git rebase staging
          git push --force-with-lease origin 
          
      - name: Create pull request into main
        uses: thomaseizinger/create-pull-request@1.2.1
        if: ${{ env.HAS_CHANGES == 'true' }}
        with:
          head: release-candidate
          base: main
          title: "[RELEASE]"
          body: |
            Release candidate for prod
            Triggered originally by @${{ github.actor }}
          labels: Release
