# This is a basic workflow to help you get started with Actions

name: cd

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [qa]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  createrelease:
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v2
      - name: Initialize mandatory git config
        run: |
          git config user.name "${{ github.actor }}"
          git config user.email ${{ github.actor }}@users.noreply.github.com
          if git ls-remote --heads origin release/production ; then exit ; git checkout qa && git checkout -b release/production && git push origin release/production; fi

      - name: Create pull request into main
        uses: thomaseizinger/create-pull-request@1.2.1
        with:
          GITHUB_TOKEN: ${{ secrets.PAT }}
          head: release/production
          base: main
          title: "[RELEASE]"
          body: |
            Author: ${{ github.actor }}
          labels: Release
