# This is a basic workflow to help you get started with Actions

name: cd

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ qa ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  createPullRequest:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          ref: qa

      - uses: actions/checkout@v3
      - name: Create commits
        run: |
          date +%s > report.txt
          git commit -am "Modify tracked file during workflow"
          date +%s > new-report.txt
          git add -A
          git commit -m "Add untracked file during workflow"

      - name: Create Pull Request
        id: cpr
        uses: peter-evans/create-pull-request@v4
        with:
          token: ${{ secrets.PAT }}
          commit-message: Release
          committer: GitHub <noreply@github.com>
          author: ${{ github.actor }} <${{ github.actor }}@users.noreply.github.com>
          signoff: false
          branch: release/qa
          base: qa
          delete-branch: true
          title: 'Release'
          body: |
            Auto-generated PR (via Github Actions manual workflow) to merge QA to RELEASE/QA. Intiated by ${{ github.actor }}.
          labels: |
            release
            automated pr
          team-reviewers: |
            owners
            maintainers
          draft: false
