name: cd

on:
  # Every time we push a new commit to MAIN branch
  push:
    branches: [main]

jobs:
  rebaseStagingWithMain:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repo
      - name: git checkout
        uses: actions/checkout@v2
        with:
          token: ${{ secrets.PAT }}
          ref: ${{ github.event.pull_request.head.ref }}
          fetch-depth: 0

      - name: Initialize mandatory git config
        run: |
          git config user.name "${{ github.actor }}"
          git config user.email ${{ github.actor }}@users.noreply.github.com

      # Creates a new branch if it doesn't exists yet
      - name: Create release branch
        uses: peterjgrainger/action-create-branch@v2.2.0
        env:
          GITHUB_TOKEN: ${{ secrets.PAT }}
        with:
          branch: "release-candidate"
          sha: "${{ github.event.pull_request.head.sha }}"

      # It will always rebase `release-candidate` with the latest `staging`
      - name: Rebase
        run: |
          git config user.name "${{ github.actor }}"
          git config user.email ${{ github.actor }}@users.noreply.github.com

          git fetch origin main
          git fetch origin staging
          git checkout staging
          git rebase main
          git push --force-with-lease origin
