name: cd

on:
  # Every time we push a new commit to MAIN branch
  push:
    branches: [main]

jobs:
  rebaseStagingWithMain:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repo
      - name: git checkout
        uses: actions/checkout@v2
        with:
          token: ${{ secrets.PAT }}
          ref: ${{ github.event.pull_request.head.ref }}
          fetch-depth: 0
          
      - name: Check for changes
        id: check-for-changes
        run: |
          if [ -z "$(git --no-pager log --left-right --cherry-pick --oneline release-candidate...staging)" ]; then
            echo "::set-output name=HAS_CHANGES::false"
          else
            echo "::set-output name=HAS_CHANGES::true"
          fi
          
      # It will always rebase `staging` with the latest `main`
      - name: Rebase
        if: ${{ steps.check-for-changes.outputs.HAS_CHANGES == 'true' }}
        run: |
          git config user.name "${{ github.actor }}"
          git config user.email ${{ github.actor }}@users.noreply.github.com

          git fetch origin main
          git fetch origin staging
          git checkout staging
          git rebase main
          git push --force-with-lease origin
